# Generated by Django 5.2.5 on 2025-08-21 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='features.feature'),
        ),
        migrations.AlterField(
            model_name='projectfeature',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='projects.project'),
        ),
    ]
