# Generated by Django 5.2.5 on 2025-08-21 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_alter_projectfeature_feature_and_more'),
        ('issues', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='assigned_developer',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='reporter',
        ),
        migrations.AddField(
            model_name='issue',
            name='project_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='features.projectfeature'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('bug', 'Bug'), ('feature_request', 'Feature Request'), ('improvement', 'Improvement')], default='bug', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='open', max_length=20),
        ),
    ]
